ktor:
    application:
        modules:
            - de.fraunhofer.iem.spha.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: ${JWT_DOMAIN}
  audience: ${JWT_AUDIENCE}
  realm: ${JWT_REALM}
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

cookie:
  key: ${COOKIE_KEY}

database:
  embedded: true
postgres:
  url: "jdbc:postgresql://localhost:5432/spha_db"
  user: postgres
  password: postgres
