name: Dependabot OSV Scan

on:
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  osv-scan:
    if: github.actor == 'dependabot[bot]'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@c5996e0193a3df57d695c1b8a1dec2a4c62e8730
    with:
      fail-on-vuln: true
      upload-sarif: false
