name: Dependabot OSV Scan

on:
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  osv-scan:
    if: github.actor == 'dependabot[bot]'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@8deb546fdb875b9996d27d4950be7312dac076a1
    with:
      fail-on-vuln: true
      upload-sarif: false
