name: Release

on:
  workflow_dispatch:
    inputs:
      SPHA_LIB_VERSION:
        description: "LIB version"
        required: true
        type: string
      SPHA_CLI_VERSION:
        description: "CLI version"
        required: true
        type: string

jobs:
  publish-cli:
    env:
      SPHA_LIB_VERSION: ${{ inputs.SPHA_LIB_VERSION }}
      SPHA_CLI_VERSION: ${{ inputs.SPHA_CLI_VERSION }}
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    environment: Deploy
    steps:
      # TODO: For CLI version this will be different
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          ref: ${{ env.SPHA_LIB_VERSION }}
      - name: Set up Apache Maven Central
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2

      - name: Package distribution
        run: ./gradlew distZip

      # TODO build and and publish to github releases

      # XXX: no official releases with changelog for CLI?