name: Release lib

on:
  workflow_dispatch:
    inputs:
      SPHA_LIB_VERSION:
        description: "LIB version and tag"
        required: true
        type: string

jobs:
  publish-lib:
    env:
      SPHA_LIB_VERSION: ${{ inputs.SPHA_LIB_VERSION }}
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    environment: Deploy
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          ref: ${{ env.SPHA_LIB_VERSION }}
      - name: Set up Apache Maven Central
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92

      - name: Publish lib to Maven Central
        env:
          SPHA_LIB_VERSION: ${{ env.SPHA_LIB_VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USER }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PW }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
        run: ./gradlew :lib:core:publishToMavenCentral :lib:adapter:publishToMavenCentral :lib:model:publishToMavenCentral --no-configuration-cache
